export const fakeSliderData  = [
  {   id:0,
    img: "https://image.tmdb.org/t/p/original/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    lThumb:"https://image.tmdb.org/t/p/original/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
    title: "The Tomorrow Job",
    videoId: "zeKp69CY47Y",
    titleImg:"https://image.tmdb.org/t/p/original/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    // movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Tomorrow Job (2023)/The.Tomorrow.Job.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    rating: 4.85,
    year:2023,
    genre:[],
    category: "Si-Fi",
    length:"2h 12m",
  },
  {
    id:1,
    img: "https://image.tmdb.org/t/p/original/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    lThumb:"https://image.tmdb.org/t/p/original/zAepSrO99owYwQqi0QG2AS0dHXw.jpg",
    title: "James Bond Quantum of Solace",
    titleImg:"https://image.tmdb.org/t/p/original/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    videoId: "BBqYaFEWBxI",
    // movieLink:"http://103.68.104.71/Data/movies/hollywood/2008/James Bond Quantum of Solace (2008)/James.Bond.Quantum.of.Solace.2008.720p.BRrip.x264.YIFY.mp4",
    rating: 3.75,
    year:2023,
    genre:[],
    category: "Action",
    length:"1h 39m",
  },
  {   id:2,
    img: "https://image.tmdb.org/t/p/original/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg",
    lThumb:"https://image.tmdb.org/t/p/original/39LxWqvQCsbAe0Cm2B7dtBe3Rd4.jpg",
    title: "The secret Kingdom",
    videoId: "h6TxL-C7zqA",
    // movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Secret Kingdom (2023)/The.Secret.Kingdom.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    titleImg:"https://image.tmdb.org/t/p/original/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg",
    rating: 4.23,
    year:2021,
    genre:[],
    category: "Adventure",
    length:"2h 39m",
  },
  {   id:3,
    img: "https://image.tmdb.org/t/p/original/phmjv93zEwitWLJEOvlXPhtK58o.jpg",
    lThumb:"https://image.tmdb.org/t/p/original/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
    title: "The Retual Killer",
    videoId: "DIa__DpZX9U",
    // movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Ritual Killer (2023)/The.Ritual.Killer.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    titleImg:"https://image.tmdb.org/t/p/original/phmjv93zEwitWLJEOvlXPhtK58o.jpg",
    rating: 3.75,
    year:2013,
    genre:[],
    category: "Action",
    length:"1h 56m",
  },
  {   id:4,
    img: "https://image.tmdb.org/t/p/original/sMp34cNKjIb18UBOCoAv4DpCxwY.jpg",
    lThumb:"https://image.tmdb.org/t/p/original/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
    title: "Damsel",
    videoId: "DIa__DpZX9Uds",
    // movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Ritual Killer (2023)/The.Ritual.Killer.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    titleImg:"https://image.tmdb.org/t/p/original/sMp34cNKjIb18UBOCoAv4DpCxwY.jpg",
    rating: 3.75,
    year:2013,
    genre:[],
    category: "Action",
    length:"1h 56m",
  },
  {   id:5,
    img: "https://image.tmdb.org/t/p/original/wShcJSKMFg1Dy1yq7kEZuay6pLS.jpg",
    lThumb:"https://image.tmdb.org/t/p/original/oFAukXiMPrwLpbulGmB5suEZlrm.jpg",
    title: "Sri Asih",
    videoId: "DIa__DpZX9Uds",
    // movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Ritual Killer (2023)/The.Ritual.Killer.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    titleImg:"https://image.tmdb.org/t/p/original/wShcJSKMFg1Dy1yq7kEZuay6pLS.jpg",
    rating: 3.75,
    year:2013,
    genre:[],
    category: "Action",
    length:"1h 56m",
  },
]
const allLiveTvData = [
  {
    id: 0,
    title: 'Movies',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 1,
    title: 'TV Series',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 2,
    title: 'Genre',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 3,
    title: 'Live TV',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 4,
    title: 'Request',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 5,
    title: 'Movies',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 6,
    title: 'TV Series',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 7,
    title: 'Genre',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 8,
    title: 'Live TV',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 9,
    title: 'Request',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 10,
    title: 'Movies',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 11,
    title: 'TV Series',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 12,
    title: 'Genre',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 13,
    title: 'Live TV',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 14,
    title: 'Request',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
];
var continueWatchingData=[
  {
    id:0,
    title:"Killer",
    thumb:"./assets/images/continue-watching/0.png",
    imdbRating:8.5,
    watchDate:"2023-12-17",
    watchTime:20,
    remainingTime:"2h 17m remaining"
  },
  {
    id:1,
    title:"Noah",
    thumb:"./assets/images/continue-watching/1.png",
    imdbRating:8.5,
    watchDate:"2023-12-17",
    watchTime:30,
    remainingTime:"2h 17m remaining"
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"./assets/images/continue-watching/2.png",
    imdbRating:8.5,
    watchDate:"2023-12-16",
    watchTime:75,
    remainingTime:"2h 17m remaining"
  },
  {
    id:3,
    title:"Kill",
    thumb:"./assets/images/continue-watching/3.png",
    imdbRating:8.5,
    watchDate:"2023-12-15",
    watchTime:10,
    remainingTime:"2h 17m remaining"
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"./assets/images/continue-watching/4.png",
    imdbRating:8.5,
    watchDate:"2023-12-20",
    watchTime:50,
    remainingTime:"2h 17m remaining"
  },

];
var recentlyAddedData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",

  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",

  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",

  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",

  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",

  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",

  },

];
var recommendedForYouData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var topMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var hollywoodMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var bollywoodMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var animationMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var banglaMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var tamilMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var hindiDubbedData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var teleguDubbedData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var imdbTop250MoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];

const liveTVsliderData = [
  { id: 0, name: "Desh TV" },
  { id: 1, name: "Baishakhi TV" },
  { id: 2, name: "NTV" },
  { id: 3, name: "Channel 24" },
  { id: 4, name: "ATN Bangla" },
  { id: 5, name: "Banglavision" },
  { id: 6, name: "Maasranga Television" },
  { id: 7, name: "Boishakhi Television" },
  { id: 8, name: "Gazi TV" },
  { id: 9, name: "Asian TV" }
];

