 export const movieData = [
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
        "genre_ids": [28, 12, 16, 35, 10751],
        "id": 1011985,
        "original_language": "en",
        "original_title": "Kung Fu Panda 4",
        "overview": "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
        "popularity": 4028.167,
        "poster_path": "https://image.tmdb.org/t/p/original/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
        "release_date": "2024-03-02",
        "title": "Kung Fu Panda 4",
        "video": false,
        "vote_average": 6.938,
        "vote_count": 379
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/zAepSrO99owYwQqi0QG2AS0dHXw.jpg",
        "genre_ids": [28, 14],
        "id": 634492,
        "original_language": "en",
        "original_title": "Madame Web",
        "overview": "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
        "popularity": 2201.481,
        "poster_path": "https://image.tmdb.org/t/p/original/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
        "release_date": "2024-02-14",
        "title": "Madame Web",
        "video": false,
        "vote_average": 5.632,
        "vote_count": 827
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/39LxWqvQCsbAe0Cm2B7dtBe3Rd4.jpg",
        "genre_ids": [28, 53],
        "id": 359410,
        "original_language": "en",
        "original_title": "Road House",
        "overview": "Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.",
        "popularity": 2562.018,
        "poster_path": "https://image.tmdb.org/t/p/original/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg",
        "release_date": "2024-03-08",
        "title": "Road House",
        "video": false,
        "vote_average": 7.267,
        "vote_count": 759
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
        "genre_ids": [28, 878, 12],
        "id": 823464,
        "original_language": "en",
        "original_title": "Godzilla x Kong: The New Empire",
        "overview": "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
        "popularity": 2461.857,
        "poster_path": "https://image.tmdb.org/t/p/original/phmjv93zEwitWLJEOvlXPhtK58o.jpg",
        "release_date": "2024-03-27",
        "title": "Godzilla x Kong: The New Empire",
        "video": false,
        "vote_average": 7.5,
        "vote_count": 81
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
        "genre_ids": [14, 28, 12],
        "id": 763215,
        "original_language": "en",
        "original_title": "Damsel",
        "overview": "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
        "popularity": 1271.706,
        "poster_path": "https://image.tmdb.org/t/p/original/sMp34cNKjIb18UBOCoAv4DpCxwY.jpg",
        "release_date": "2024-03-07",
        "title": "Damsel",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 1253
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/oFAukXiMPrwLpbulGmB5suEZlrm.jpg",
        "genre_ids": [28, 12, 878, 14, 18],
        "id": 624091,
        "original_language": "id",
        "original_title": "Sri Asih",
        "overview": "Alana discover the truth about her origin: she’s not an ordinary human being. She may be the gift for humanity and become its protector as Sri Asih. Or a destruction, if she can’t control her anger.",
        "popularity": 1103.298,
        "poster_path": "https://image.tmdb.org/t/p/original/wShcJSKMFg1Dy1yq7kEZuay6pLS.jpg",
        "release_date": "2022-11-17",
        "title": "Sri Asih",
        "video": false,
        "vote_average": 6.288,
        "vote_count": 40
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg",
        "genre_ids": [878, 28, 14, 12],
        "id": 601796,
        "original_language": "ko",
        "original_title": "외계+인 1부",
        "overview": "In the year 2022, a Robot Guard manages alien prisoners trapped inside human brains. Raising the young girl Ean on Earth, he lives in the guise of a human being. One day, when an alien prisoner escapes, the entire planet is thrown into jeopardy and Guard goes back to the past with Ean to trap the alien there. Meanwhile 630 years earlier during the Goryeo Dynasty, an older Ean is known as 'The Girl Who Shoots Thunder'. While Ean is trying to retrieve the Divine Blade, the key to traveling through time, Muruk, a hapless dosa (Korean tao magician), is aiming to claim the enormous bounty placed on it.",
        "popularity": 1337.194,
        "poster_path": "https://image.tmdb.org/t/p/original/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg",
        "release_date": "2022-07-20",
        "title": "Alienoid",
        "video": false,
        "vote_average": 7.16,
        "vote_count": 212
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/2C3CdVzINUm5Cm1lrbT2uiRstwX.jpg",
        "genre_ids": [28, 14, 10752],
        "id": 856289,
        "original_language": "zh",
        "original_title": "封神第一部：朝歌风云",
        "overview": "Based on the most well-known classical fantasy novel of China, Fengshenyanyi, the trilogy is a magnificent eastern high fantasy epic that recreates the prolonged mythical wars between humans, immortals and monsters, which happened more than three thousand years ago.",
        "popularity": 1257.326,
        "poster_path": "https://image.tmdb.org/t/p/original/kUKEwAoWe4Uyt8sFmtp5S86rlBk.jpg",
        "release_date": "2023-07-20",
        "title": "Creation of the Gods I: Kingdom of Storms",
        "video": false,
        "vote_average": 7.273,
        "vote_count": 130
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/mDeUmPe4MF35WWlAqj4QFX5UauJ.jpg",
        "genre_ids": [28, 27, 53],
        "id": 1096197,
        "original_language": "pt",
        "original_title": "No Way Up",
        "overview": "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
        "popularity": 999.449,
        "poster_path": "https://image.tmdb.org/t/p/original/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
        "release_date": "2024-01-18",
        "title": "No Way Up",
        "video": false,
        "vote_average": 6.209,
        "vote_count": 290
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/meyhnvssZOPPjud4F1CjOb4snET.jpg",
        "genre_ids": [16, 28, 12, 35, 10751],
        "id": 940551,
        "original_language": "en",
        "original_title": "Migration",
        "overview": "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
        "popularity": 935.68,
        "poster_path": "https://image.tmdb.org/t/p/original/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
        "release_date": "2023-12-06",
        "title": "Migration",
        "video": false,
        "vote_average": 7.564,
        "vote_count": 1017
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/87IVlclAfWL6mdicU1DDuxdwXwe.jpg",
        "genre_ids": [878, 12],
        "id": 693134,
        "original_language": "en",
        "original_title": "Dune: Part Two",
        "overview": "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
        "popularity": 778.73,
        "poster_path": "https://image.tmdb.org/t/p/original/czembW0Rk1Ke7lCJGahbOhdCuhV.jpg",
        "release_date": "2024-02-27",
        "title": "Dune: Part Two",
        "video": false,
        "vote_average": 8.4,
        "vote_count": 2216
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/xvk5AhfhgQcTuaCQyq3XqAnhEma.jpg",
        "genre_ids": [28],
        "id": 1006540,
        "original_language": "en",
        "original_title": "Bullet Train Down",
        "overview": "On its maiden run, the world's fastest bullet train is rigged with a bomb that will explode if it dips below 200 mph.",
        "popularity": 941.257,
        "poster_path": "https://image.tmdb.org/t/p/original/5a7cocgyVuFjYV71neDIGVzD6Yq.jpg",
        "release_date": "2022-08-01",
        "title": "Bullet Train Down",
        "video": false,
        "vote_average": 5.075,
        "vote_count": 20
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/u0P5drNyTrZoGyJONPcZGbv1mNP.jpg",
        "genre_ids": [28, 53],
        "id": 1124127,
        "original_language": "en",
        "original_title": "Air Force One Down",
        "overview": "On her first assignment aboard Air Force One, a rookie Secret Service agent faces the ultimate test when terrorists hijack the plane, intent on derailing a pivotal energy deal. With the President's life on the line and a global crisis at stake, her bravery and skills are pushed to the limit in a relentless battle that could change the course of history.",
        "popularity": 763.229,
        "poster_path": "https://image.tmdb.org/t/p/original/nKPoSD4pZ3s3CJ9g3cqWRcQ41TC.jpg",
        "release_date": "2024-02-09",
        "title": "Air Force One Down",
        "video": false,
        "vote_average": 6.37,
        "vote_count": 46
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/oFS0DgInCdvYRwaPkl3BLpmIuq5.jpg",
        "genre_ids": [28, 80, 18, 9648, 878, 53],
        "id": 1013240,
        "original_language": "id",
        "original_title": "24 Jam Bersama Gaspar",
        "overview": "With only 24 hours left to live, a private investigator follows a trail of confounding clues to uncover the disappearance of his childhood friend.",
        "popularity": 804.367,
        "poster_path": "https://image.tmdb.org/t/p/original/8jJKM0ZR3GQo6E3CUkMKKVa4S8B.jpg",
        "release_date": "2023-10-06",
        "title": "24 Hours with Gaspar",
        "video": false,
        "vote_average": 7.095,
        "vote_count": 21
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/cu5Qk2QHxOyyMrD3Bq93DxgmJer.jpg",
        "genre_ids": [28, 80],
        "id": 1046090,
        "original_language": "zh",
        "original_title": "周處除三害",
        "overview": "The arrogant, third most-wanted criminal in Taiwan, decides to get rid of the top two competitors and crowns himself the most-wanted criminal before dying.",
        "popularity": 728.272,
        "poster_path": "https://image.tmdb.org/t/p/original/7IJ7F8tX7IAkpUdaGovOBJqORnJ.jpg",
        "release_date": "2023-10-06",
        "title": "The Pig, the Snake and the Pigeon",
        "video": false,
        "vote_average": 7.555,
        "vote_count": 109
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/4Ep2KivIBUZbkS7kHjW7Qywnhhj.jpg",
        "genre_ids": [16, 35, 878],
        "id": 1239251,
        "original_language": "en",
        "original_title": "Megamind vs. the Doom Syndicate",
        "overview": "Megamind's former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.",
        "popularity": 729.8,
        "poster_path": "https://image.tmdb.org/t/p/original/yRZfiG1QpRkBc7fAmxfcR7Md5EC.jpg",
        "release_date": "2024-03-01",
        "title": "Megamind vs. the Doom Syndicate",
        "video": false,
        "vote_average": 5.7,
        "vote_count": 137
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/ekRp1sEA8pnuzVHQkUESTgNSKdW.jpg",
        "genre_ids": [878, 28, 80],
        "id": 932420,
        "original_language": "en",
        "original_title": "Code 8 Part II",
        "overview": "In a world where superpowered people are heavily policed by robots, an ex-con teams up with a drug lord he despises to protect a teen from a corrupt cop.",
        "popularity": 753.988,
        "poster_path": "https://image.tmdb.org/t/p/original/hhvMTxlTZtnCOe7YFhod9uz3m37.jpg",
        "release_date": "2024-02-27",
        "title": "Code 8 Part II",
        "video": false,
        "vote_average": 6.496,
        "vote_count": 360
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/qVrS8bu1B7G1tgLTlCZQi4CFsTh.jpg",
        "genre_ids": [28, 53, 10752],
        "id": 969492,
        "original_language": "en",
        "original_title": "Land of Bad",
        "overview": "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
        "popularity": 768.397,
        "poster_path": "https://image.tmdb.org/t/p/original/h3jYanWMEJq6JJsCopy1h7cT2Hs.jpg",
        "release_date": "2024-01-25",
        "title": "Land of Bad",
        "video": false,
        "vote_average": 7.119,
        "vote_count": 431
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/o5gQcU7L6JjY7qpLzhVeAmIJvVl.jpg",
        "genre_ids": [28, 80, 18, 53],
        "id": 729896,
        "original_language": "en",
        "original_title": "Sagittarius A",
        "overview": "After a routine mission goes wrong, a military pilot tries to survive in an alien landscape while being hunted by a sentient spacecraft.",
        "popularity": 650.481,
        "poster_path": "https://image.tmdb.org/t/p/original/8vCJ6GT28a0BTU0U0OFLJJjQIeD.jpg",
        "release_date": "2023-06-07",
        "title": "Sagittarius A",
        "video": false,
        "vote_average": 6.623,
        "vote_count": 97
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/7ChTzE8yULW1lzJ0MyIhBBxdUQf.jpg",
        "genre_ids": [28, 12, 35, 14],
        "id": 817100,
        "original_language": "en",
        "original_title": "The Great Hike",
        "overview": "When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.",
        "popularity": 674.303,
        "poster_path": "https://image.tmdb.org/t/p/original/pZFLXVMykTdIjZg8igirZq35DrQ.jpg",
        "release_date": "2023-08-17",
        "title": "The Great Hike",
        "video": false,
        "vote_average": 6.219,
        "vote_count": 161
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/5v6kPe7egyBZjkFIIWvg9dYNSHe.jpg",
        "genre_ids": [28, 80, 18],
        "id": 906074,
        "original_language": "en",
        "original_title": "Burn Notice: A New Day",
        "overview": "Set after the events of the Burn Notice series finale, former spy Michael Westen goes toe-to-toe with a criminal cartel in search of his missing fiancée, while also uncovering the truth about his mother's sudden disappearance. Burn Notice: A New Day is a feature-length continuation that takes place after the events of the original television series.",
        "popularity": 591.499,
        "poster_path": "https://image.tmdb.org/t/p/original/bLT6yoQ7tC5eEj4be3r06tx0c4f.jpg",
        "release_date": "2023-08-10",
        "title": "Burn Notice: A New Day",
        "video": false,
        "vote_average": 7.045,
        "vote_count": 23
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/yInQhqMgvgW6XvjFlHzN2FANP25.jpg",
        "genre_ids": [16, 10751],
        "id": 1195121,
        "original_language": "en",
        "original_title": "The Ark and the Aardvark",
        "overview": "In this epic adventure, a plucky aardvark named Gilbert is transformed into a creature of mythical proportions after he unearths an ancient artifact.",
        "popularity": 601.606,
        "poster_path": "https://image.tmdb.org/t/p/original/9ff0cF8J8ZCtjlRLGl6kPdZGjo8.jpg",
        "release_date": "2023-11-17",
        "title": "The Ark and the Aardvark",
        "video": false,
        "vote_average": 6.272,
        "vote_count": 54
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/zILgt4HrwP9DNvZraGs5e9XM8je.jpg",
        "genre_ids": [28, 878, 53, 10752],
        "id": 868316,
        "original_language": "en",
        "original_title": "Battle for Elestra",
        "overview": "A warrior named Da Hufa goes to save his prince from a dystopian village ruled by a demonic overlord. In search of his prince, he meets a Fox demon who helps him along the way. But can he trust her?",
        "popularity": 552.285,
        "poster_path": "https://image.tmdb.org/t/p/original/7UR4aQFAL5Y5gbNl0J1G5LkHDs1.jpg",
        "release_date": "2024-01-26",
        "title": "Battle for Elestra",
        "video": false,
        "vote_average": 6.923,
        "vote_count": 126
      },
      {
        "adult": false,
        "backdrop_path": "https://image.tmdb.org/t/p/original/5I4fVKxSX48et3p6cYaXQ8AZ5VJ.jpg",
        "genre_ids": [28, 12, 18],
        "id": 770455,
        "original_language": "en",
        "original_title": "Death on the Nile: Act Two",
        "overview": "As Hercule Poirot enjoys a luxurious cruise down the Nile, a newlywed heiress is found murdered on board. Can Poirot identify the killer among a slew of suspects, or will he fall prey to the murderer first?",
        "popularity": 539.29,
        "poster_path": "https://image.tmdb.org/t/p/original/8TKe55VMHK3hXitY63DIhTOmB6v.jpg",
        "release_date": "2024-03-14",
        "title": "Death on the Nile: Act Two",
        "video": false,
        "vote_average": 7.21,
        "vote_count": 241
      }
    ]
